language: node_js

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - bash <(curl -s https://blackbaud.github.io/skyux-travis/library-before-install.sh)

after_success:
  - chmod +x ./scripts/publish.sh
  - ./scripts/publish.sh

script:
  - skyux test && skyux build
