language: node_js
dist: xenial

services:
  - xvfb

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

before_install:
  - npm install -g @blackbaud/skyux-cli

after_success:
  - chmod +x ./scripts/publish.sh
  - ./scripts/publish.sh

script:
  - skyux test && skyux build
