name: Test, Build, and Deploy

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm i

      - run: npx -p @skyux-sdk/cli skyux test --headless

      - run: npx -p @skyux-sdk/cli skyux build

      - run: cp dist/index.html dist/404.html
        if: ${{ success() && github.event_name == 'push' }}

      - uses: crazy-max/ghaction-github-pages@v2
        if: ${{ success() && github.event_name == 'push' }}
        with:
          repo: bobbyearl/traffic
          target_branch: master
          keep_history: true
          build_dir: dist
          commit_message: "Build for ${{ github.sha }}"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
